# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gostacking < Formula
  desc "Git stacking using merge"
  homepage "https://github.com/Bhacaz/gostacking"
  version "0.10.2"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.10.2/gostacking_Darwin_arm64.tar.gz"
    sha256 "6af8f4991ac5768987b2066f8302408d039b9c1ef8cbadb1f5f03ac0505315df"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
  if Hardware::CPU.intel?
    url "https://github.com/Bhacaz/gostacking/releases/download/v0.10.2/gostacking_Darwin_x86_64.tar.gz"
    sha256 "48b1a4ceb1da5f0585964d3e719fd184d663cd5ab85b2be2f85d43149097c19f"

    def install
      bin.install "gostacking"
      zsh_completion.install "completions/gostacking.zsh" => "_gostacking"
    end
  end
end
